[custom.all.idris2-http-types]
type = "local"
path = "."
ipkg = "idris2-http-types.ipkg"

[custom.all.bytestring]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-bytestring"
commit = "latest:main"
ipkg   = "bytestring.ipkg"
